
name: Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      run: |
        python main.py
    - name: Upload files
      shell: bash
      run: gh release upload ${{ github.event.release.tag_name }} build/*
      env:
        GITHUB_TOKEN: ${{ github.token }}
